version: '3'

services:
  prom_node_exporter:
    image: prom/node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
    pid: host
    command:
      - --path.rootfs=/host

  prom_prometheus:
    image: prom/prometheus
    extra_hosts:
      - dockerhost:172.17.0.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_prometheus_volume:/prometheus

  prom_grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    volumes:
      - prom_grafana_volume:/var/lib/grafana


volumes:
  prom_prometheus_volume:
  prom_grafana_volume:
