version: '3'

services:
  prometheus:
    image: prom/prometheus
    extra_hosts:
      - dockerhost:172.17.0.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: always

  node_exporter:
    image: prom/node-exporter
    network_mode: host
    volumes:
      - /:/host:ro
    pid: host
    command:
      - --path.rootfs=/host
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always


volumes:
  prometheus_data:
  grafana_data: